### ISSUE TITLE
No such file or directory: '../preprocess_data/X_val.npy'

### ISSUE THREAD

**Issue by ysl208** [omidmnezami/Engagement-Recognition#10]
I followed the instructions to test the model but am getting an error for a missing file in `preprocess_data/X_val.npy`. 

```
Instructions for updating:
non-resource variables are not supported in the long term
Scipy not supported!
Traceback (most recent call last):
  File "ER_model.py", line 161, in <module>
    network.load_saved_dataset()
  File "ER_model.py", line 80, in load_saved_dataset
    self.dataset.load_from_save()
  File "/home/sheryl/Projects/Engagement-Recognition/code/VGG_dataset_loader.py", line 24, in load_from_save
    self._images_valid = np.load(join(SAVE_DIRECTORY_DATA, SAVE_DATASET_IMAGES_VALID_FILENAME))
  File "/home/sheryl/anaconda3/envs/ER/lib/python2.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
IOError: [Errno 2] No such file or directory: '../preprocess_data/X_val.npy'
```

Any advice? my `preprocess_data` folder only contains `X_train.npy` and `Y_train.npy`.

**Comment by Cip0** [comment]
Did you solve the problem?

**Comment by ysl208** [comment]
The command `python ER_model.py test` needs to be run inside the `code/` folder.
