### ISSUE TITLE
tensorflow.compat.v1 Error

### ISSUE THREAD

**Issue by yogidosalwar** [omidmnezami/Engagement-Recognition#11]
HI @omidmnezami 

I have installed all dependencies as per your requirement, but still getting the error.  

while testing python ER_model.py test

File "ER_model.py", line 4, in <module>
    import tflearn
  File "/home/lib/python2.7/site-packages/tflearn/__init__.py", line 4, in <module>
    import tensorflow.compat.v1 as tf
ImportError: No module named compat.v1

Thank you!!

**Comment by omidmnezami** [comment]
@yogidosalwar 

This error is because of the version of your TensorFlow.
Please make sure you install the right version:

pip install tensorflow==1.8.0

You may also check the version by:

````
import tensorflow as tf
print(tf.__version__)

````
Thanks

**Comment by TorAP** [comment]
Hello @omidmnezami 

I still get this error, even though I have the tensorflow = 1.8.0.

>> python ER_model.py train

Traceback (most recent call last):
  File "ER_model.py", line 4, in <module>
    import tflearn
  File "/User/opt/anaconda3/envs/py2/lib/python2.7/site-packages/tflearn/__init__.py", line 4, in <module>
    import tensorflow.compat.v1 as tf
ImportError: No module named compat.v1

**Comment by omidmnezami** [comment]
@TorArnthPetersen 

This error is because of importing tflearn with an incompatible version of Tensorflow. Please try a version lower that 1.8.0 if it doesn't work. (1.8.0 works fine on my system though.)

**Comment by sanxchep** [comment]
@omidmnezami What is your tflearn version?

and if possible can you do a pip freeze for all the packages required to requirement.txt?
