### ISSUE TITLE
No such file or directory: '../model/X_train.npy'

### ISSUE THREAD

**Issue by arlla** [omidmnezami/Engagement-Recognition#3]
WARNING:tensorflow:From /home/arllaptop/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "VGG_model.py", line 161, in <module>
    network.load_saved_dataset()
  File "VGG_model.py", line 80, in load_saved_dataset
    self.dataset.load_from_save()
  File "/home/arllaptop/Desktop/Engagement-Recognition-master/code/VGG_dataset_loader.py", line 12, in load_from_save
    self._images = np.load(join(SAVE_DIRECTORY, SAVE_DATASET_IMAGES_FILENAME))
  File "/home/arllaptop/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
IOError: [Errno 2] No such file or directory: '../model/X_train.npy'

Please provide "*.npy" files.

**Comment by ysl208** [comment]
I am getting the same error but for the X_val.npy file:
```
IOError: [Errno 2] No such file or directory: '../preprocess_data/X_val.npy'
```
